### ISSUE TITLE
How does one generate the codegen.ts file?

### ISSUE THREAD

**Issue by rarenatoe** [ticruz38/graphql-codegen-svelte-apollo#14]
In the documentation I see I have to install graphql-codegen-svelte-apollo, but later no further instructions are given.

Then when I head into the example, the file package.json doesn't even contain graphql-codegen-svelte-apollo, which throws the entire thing aobut installing graphql-codegen-svelte-apollo out of the window. Instead I am insinuated that I need to create a script `"types": "cross-env DEBUG=1 && graphql-codegen",` which uses `graphql-codegen` which was never talked about in the README.md ...

I'm very confused and I would appreciate it if I could get some clear directions.

Thank you.

**Comment by jycouet** [comment]
`graphql-codegen-svelte-apollo` is a plugin part of an ecosystem called: [graphql-code-generator](https://www.graphql-code-generator.com/) (You can find the info in the readme!)

To use, `graphql-codegen-svelte-apollo`, you have to setup `graphql-codegen` and configure it well. (You have an example of [codegen.yml](https://github.com/ticruz38/graphql-codegen-svelte-apollo/blob/main/example/codegen.yml) in the example folder)

Did you look at the readme of the example?
it's written:
![image](https://user-images.githubusercontent.com/5312607/113556073-33e6e800-95fc-11eb-95df-cb550db25b57.png)

The example is setup for developers of `graphql-codegen-svelte-apollo`, but it's explained how to turn it as User of the plugin.


I hope it's helping you 🚀

**Comment by ticruz38** [comment]
@rarenatoe  I have updated the readme to include all the dependencies you will need to install. It also refer to graphql-codegen for further documentation on how to use codegen.yml
All you will need after that is an apollo-client, you can see an example [here](https://github.com/ticruz38/graphql-codegen-svelte-apollo/blob/main/example/src/apollo-client.ts). Then of course, you need a graphQL server to point to.
