### ISSUE TITLE
Cannot build app when TS has strictNullChecks enabled

### ISSUE THREAD

**Issue by rarenatoe** [ticruz38/graphql-codegen-svelte-apollo#16]
When running the app on dev mode everything works fine, however when I build it in order to deploy it to the cloud (`cross-env NODE_ENV=production sapper build --legacy`), I am met with errors:

```
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2322: Type 'null' is not assignable to type 'ProductsQueryQuery'.
  Type 'null' is not assignable to type '{ __typename?: "Query" | undefined; }'.


458               { data: null, loading: true, error: null, networkStatus: 1, query: null },
                    ~~~~

  node_modules/@apollo/client/core/types.d.ts:18:5
    18     data: T;
           ~~~~
    The expected type comes from property 'data' which is declared here on type 'ApolloQueryResult<ProductsQueryQuery> & { query: ObservableQuery<ProductsQueryQuery, Exact<{ [key: string]: never; }>>; }'
```

When I go to the codegen.ts file, I am met with these errors:
<img width="1083" alt="Screen Shot 2021-05-08 at 20 00 15" src="https://user-images.githubusercontent.com/44821537/117557376-d9480e00-b037-11eb-9721-142d99dca1bd.png">

I have updated all the relevant dependencies, but that doesn't seem to fix it.

The only thing that has worked so far for me has been to disable `strictNullChecks`, but this method feels a little cheap to me and would like to know if there is a better way to work it out.

**Comment by ticruz38** [comment]
You may add the codegen file to the excludes list in tsconfig.json, let me know if this fixes your problem.

It is better to exclude this file from type-checking also for the speed of your editor (as you would do for node_modules).

**Comment by rarenatoe** [comment]
Thanks, will do. Not the solution I was expecting, but I get it 👍 .

**Comment by rarenatoe** [comment]
Excluding it in tsconfig.json brings me the following issue, when running `yarn sapper dev`:
```
Unexpected token (Note that you need plugins to import files that are not JavaScript)
1: import client from "./src/lib/apollo";
2: import type {
               ^
3:         ApolloQueryResult, ObservableQuery, WatchQueryOptions
4:       } from "@apollo/client";
internal/modules/cjs/loader.js:883
  throw err;
```

I'm not sure what it exactly means, but from what I've seen, it's probably something to do with `@rollup/plugin-typescript`.

Any ideas on how to go about this?

Thank you for you time.
Ren.

**Comment by ticruz38** [comment]
depending on your config, the `type` keyword is needed or not, that would be my best guess...
