### ISSUE TITLE
Svelte Apollo plugin

### ISSUE THREAD

**Issue by jycouet** [ticruz38/graphql-codegen-svelte-apollo#17]
Hi @ticruz38,
I'm working with the plugin for about 6 months, and it's working like a charm 👍.

I came across https://github.com/dotansimha/graphql-code-generator/issues/5957 issue and find it a bit strange to not talk about it here before.

I mean, in the open source community we should try to put all our energy in common. Right?
So I open this issue here to start the exchange and see if we can do something in common.

I'm looking forward to your views/opinions 👍

**Comment by ticruz38** [comment]
We could easily integrate this plugin to graphql-code-generator directly for sure. This plugin has almost no dependencies except Apollo and GraphQL.
I don't know which steps needs to be completed to land this plugin on their website, we should probably send a pull request to their repo.

**Comment by Urigo** [comment]
I don't think there is any benefit on moving this great library in the base repo.
One of [The Guild's core principals](https://the-guild.dev/about-us) for sustainable open source and supporting and encouragement of the individuals who create open source like yourself.
All of The Guild's libraries are under individual names and not under The Guild's Github org for the same reason.

If there is something we can do to support you better or highlight the library in a better way, let us know!

**Comment by Urigo** [comment]
and I'm very happy you jumped into that discussion, thank you for that!

**Comment by ticruz38** [comment]
> I don't think there is any benefit on moving this great library in the base repo.
> One of [The Guild's core principals](https://the-guild.dev/about-us) for sustainable open source and supporting and encouragement of the individuals who create open source like yourself.
> All of The Guild's libraries are under individual names and not under The Guild's Github org for the same reason.
> 


Yes that's what I thought, graphql-code-generator is the framework you build on. There is no reason to bloat the core repository with hundreds of plugin and their dependencies.
So we agree that this plugin lives in the right place.

> If there is something we can do to support you better or highlight the library in a better way, let us know!

Exactly, I think there should be something on the website advertising this plugin for svelte users.

Thanks @Urigo !

**Comment by Urigo** [comment]
@ticruz38 awesome!  could you submit a PR for the docs that puts Svelte Apollo Plugin in all the right places?

**Comment by ticruz38** [comment]
> @ticruz38 awesome! could you submit a PR for the docs that puts Svelte Apollo Plugin in all the right places?

Sure! I'm seriously busy right now, but I'll ship it before the end of next week.
