### ISSUE TITLE
Docs question, esp Async section

### ISSUE THREAD

**Issue by jeremybradbury** [ticruz38/graphql-codegen-svelte-apollo#21]
Copied from: https://github.com/dotansimha/graphql-code-generator/discussions/6434

This seemed like a better place to post this, but I wanted to also check with the larger group, that it wasn't some obvious user error.

RE: https://github.com/ticruz38/graphql-codegen-svelte-apollo#with-async-queries

the beginning of this section says:
```
query Transactions($address: String) {
    transactions(address: $address) {
        ...TransactionFragment
    }
}
```
but then later shows this, however this magic new AsyncTransactions is not generated. I believe this is an omission/mistake in the above query's name?

```
<script lang="ts">
  import { AsyncTransactions } from "codegen";

  var address = "0x0000000000000000000000000000"
</script>

<ul>
  {#await AsyncTransactions({ address })}
    Loading...
  {:then transactions}
    {#each transactions || [] as transaction}
        <li>Sent transaction from {transaction.from} to {transaction.to}</li>
    {/each}
  {/await}
</ul>
```

When I use Svelte as documented above (in node 14/stable), using the #await on a query, the api call is never even fired from the browser.

In contrast when I treat this simply as an observable, the api call shows a successful result in the network tab but never updates the observable in the dom, then triggers a cannot map of undefined or similar such problem where it should have an empty array or results when truthy.

I have only been able to get mutations and subscriptions working so far. What's the secret sauce for simple queries without any variables?

**Comment by jeremybradbury** [comment]
I traced that back and added a null check to my code, so that the above error is no longer even a possible cause. 

now when observing, my $query.loading changes and it will work.

I just need to get the result, and then do some sorting/mapping/filtering of array data in the ui, before I render a table or chart, perhaps an onUpdate hook to handle form changes.

but i cannot seem to even get a result out of the query promise using async, even when implemented like a mutation, which does return data.

I have a path forward with observables... but I still can't seem to get async working using the docs.

**Comment by ticruz38** [comment]
could you share your codegen.yml config and a snippet of your code?
AsyncQuery are only generated when asyncQuery option is set to true.
