### ISSUE TITLE
data {} instead of null - bump version?

### ISSUE THREAD

**Issue by jycouet** [ticruz38/graphql-codegen-svelte-apollo#23]
Hi @ticruz38 

I wanted to update my packages and your v1.0.1 has a quite big change:
When the query is loading, data is {} now. Before it was null.

Here is the line:
https://github.com/ticruz38/graphql-codegen-svelte-apollo/commit/e87c12a4ad8deeddd4ddce2684e8080614d862c9#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R114

I was using this data null in a lot of places. Is it intended?
Hooo, I just saw https://github.com/ticruz38/graphql-codegen-svelte-apollo/issues/22 now... So I guess that yes it's intended. 

It's kind a lot of work... But I guess it's better!
Maybe you should bump the package to a v1.1? or even 2.0?

**Comment by ticruz38** [comment]
yes, I think this is what you get when you use raw apollo client, an empty data object, so it makes sense to replicate this.

you are right, will bump the version to 1.1
