### ISSUE TITLE
Basic setup question

### ISSUE THREAD

**Issue by nimmolo** [ticruz38/graphql-codegen-svelte-apollo#27]
Hi Ticruz38, thanks for your work. 

I'm just getting my head around GraphQL and experimenting with Svelte, sorry for the newbie question. 

Do I understand correctly that this plugin does not depend on [svelte-apollo](https://github.com/timhall/svelte-apollo) in any way (as discussed [in an old issue](https://github.com/ticruz38/graphql-codegen-svelte-apollo/issues/2)), and is basically a more "direct" integration of Apollo-Client with Svelte?

**Comment by nimmolo** [comment]
I get it now. Could be good to show (the very few) basic steps how to remove svelte-apollo, but it's easy.

**Comment by ticruz38** [comment]
the plugin do not depend on svelte-apollo, it generates just the bit you need with full typescript support, the usage however is quite similar I think.

**Comment by nimmolo** [comment]
thanks @ticruz38 - the usage does seem very similar. 

The problem i'm having is trying to initiate a `refetch` with different query variables, it works with svelte-apollo and the original query (document), but with the generated typescript query (and no svelte-apollo) i can't get it to refetch. I'm updating my other issue #28
