### ISSUE TITLE
How to refetch with new query variables?

### ISSUE THREAD

**Issue by nimmolo** [ticruz38/graphql-codegen-svelte-apollo#28]
(**Edited**)
Refetching with the generated query type seems to work different from the refetch function in Apollo Client `useQuery`. The refetch worked with svelte-apollo, but i'm trying to eliminate that dependency. 

I guess I don't understand if there's a different syntax - can anyone provide an example?

When I assign the generated query to a reactive constant in my Svelte front-end code, 
```svelte
$: observations = getObservations({ variables: { filter } });
```
the query does not refetch when i update the query variables, as I would expect.

This is how my svelte template is using the query. The filter object changes based on a form user input. I've tried this with an `await` block too.

```svelte
<script lang="ts">
import { getObservations } from '$lib/generated';

$: observations = getObservations({ variables: { filter } });

function handleFilter(event) {
  filter = event.detail;
}
</script>

{#if $observations.loading}
  Loading...
{:else if $observations.error}
  {$observations.error}
{:else if $observations.data}
  {#each $observations.data['observations']['edges'] as edge}
    <Item node={edge['node']} />
  {/each}
{/if}
```

Since this plugin allows to use the query directly, without Apollo's `useQuery`, i'm not sure how to phrase a refetch.
If i do `$observations.refetch();` inside `handleFilter(e)`, i get an error
```
Property 'refetch' does not exist on type 'Readable<ApolloQueryResult<GetObservationsQuery> & { query: ObservableQuery<GetObservationsQuery, Exact<{ filter?: FilterObservationsInput; }>>; }>'.ts(2339)
```

There's nothing fancy in my config. Am I doing something wrong here?

```yml
schema: src/graphql/schema.graphql
documents: 
  - src/graphql/queries.graphql
  - src/graphql/mutations.graphql
generates:
  src/lib/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - graphql-codegen-svelte-apollo
config: 
  clientPath: src/lib/shared/client
  # asyncQuery: true
  scalars:
    ISO8601Date: Date
    ISO8601DateTime: Date
```
Here's the client:
```typescript
export default new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          observations: relayStylePagination(),
        },
      },
    },
  })
});
```
The generated query:
```typescript
export const getObservations = (
            options: Omit<
              WatchQueryOptions<GetObservationsQueryVariables>, 
              "query"
            >
          ): Readable<
            ApolloQueryResult<GetObservationsQuery> & {
              query: ObservableQuery<
                GetObservationsQuery,
                GetObservationsQueryVariables
              >;
            }
          > => {
            const q = client.watchQuery({
              query: GetObservationsDoc,
              ...options,
            });
            var result = readable<
              ApolloQueryResult<GetObservationsQuery> & {
                query: ObservableQuery<
                  GetObservationsQuery,
                  GetObservationsQueryVariables
                >;
              }
            >(
              { data: {} as any, loading: true, error: undefined, networkStatus: 1, query: q },
              (set) => {
                q.subscribe((v: any) => {
                  set({ ...v, query: q });
                });
              }
            );
            return result;
          }
```
Here's the query document that it's built from:
```graphql
query getObservations($filter: FilterObservationsInput) {
  observations(filter: $filter) {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        id
        createdAt
        updatedAt
        when
        where
        imgSrcThumb
        imgSrcSm
        imgSrcMed
        thumbImage {
          width
          height
        }
        name {
          formatName
          author
        }
        user {
          name
          login
        }
        rssLog {
          detail
        }
      }
    }
  }
}
```

**Comment by nimmolo** [comment]
Reopening with rephrased question.

I'm realizing the problem is probably either my refetch is not properly phrased, or maybe the store is only hitting the cached query. I've been going over my code for days and I can't figure out what it could be. I've tried await blocks and useQuery. 

The refetch worked with `svelte-apollo`, but i'm trying to eliminate that dependency.

**Comment by nimmolo** [comment]
Is the problem maybe with using `InMemoryCache` in my client?

**Comment by nimmolo** [comment]
**Update**
Documenting the error i get with switching to an async query and using the Svelte store.

```svelte
$: observations = AsyncGetObservations({ variables: { filter } });
...
  {#await $observations}
    <p>...Loading</p>
  {:then result}
    {#if result.data?.observations?.edges}
      {#each result.data?.observations?.edges || [] as edge}
        <Item node={edge['node']} />
      {/each}
    {/if}
  {/await}
```
Error message in TypeScript
```
Argument of type 'Promise<ApolloQueryResult<GetObservationsQuery>>' is not assignable to parameter of type 'SvelteStore<any>'.ts(2345)
```

**Comment by ticruz38** [comment]
> Reopening with rephrased question.
> 
> I'm realizing the problem is probably either my refetch is not properly phrased, or maybe the store is only hitting the cached query. I've been going over my code for days and I can't figure out what it could be. I've tried await blocks and useQuery.
> 
> The refetch worked with `svelte-apollo`, but i'm trying to eliminate that dependency.

the refetch only does an http query if the cache do not already hold the same query in memory, try changing the query variables, and the refetch will be done automatically, you can change the policy for your query and set it to httpOnly.
Let me know if the behaviour is what you would expect, knowing the policy above

**Comment by nimmolo** [comment]
thank you yes - that behavior is what i would expect, but when i change query variables the query does **not** refetch. 

In the example above, the generated query is not refetching when the user changes `{ variables: { filter } }` — But if i switch back to using `svelte-apollo`'s `query` with everything else the same in the component, it does refetch. That's why I am so confused.

Here's the code that works with `svelte-apollo`:
```svelte 
import { query } from '@dxlb/svelte-apollo';
import { GET_OBSERVATIONS } from '$lib/shared/queries';

const observations = query(GET_OBSERVATIONS, { variables: { filter } });

$: observations.refetch({ filter });

function handleFilter(event) {
  filter = event.detail;
}
```
Here is the only lines that changed, i follow the example in your docs:
```svelte
import { GetObservations, AsyncGetObservations } from '$lib/generated';

$: observations = GetObservations({ variables: { filter } });
```

I console logged the `filter` to be sure that variable is still changing, and it is changing. 

If I understood `httpOnly` correctly I believe i would prefer not to set this query to that, because it's one of the most expensive in the app. It's going to be used to virtual-list-scroll up and down through 1.5M records.

But when the records are filtered by the user, that's when it should refetch.

**Comment by nimmolo** [comment]
🤔 I'd like to test httpOnly, how can i set it?  [There seems to be a current bug](https://github.com/dotansimha/graphql-code-generator/issues/6451) setting `fetchPolicy` with graphql-code-generator.

When I set 
```yml
    config:
      clientPath: "$lib/shared/client"
      asyncQuery: true
      defaultBaseOptions:
        fetchPolicy: "no-cache"
```
it still doesn't refetch

**Comment by ticruz38** [comment]
> 🤔 I'd like to test httpOnly, how can i set it? [There seems to be a current bug](https://github.com/dotansimha/graphql-code-generator/issues/6451) setting `fetchPolicy` with graphql-code-generator.
> 
> When I set
> 
> ```yaml
>     config:
>       clientPath: "$lib/shared/client"
>       asyncQuery: true
>       defaultBaseOptions:
>         fetchPolicy: "no-cache"
> ```
> 
> it still doesn't refetch

You can pass in options at the query level,

to use refetch, do `$observations.query.refetch()`

the refetch does not trigger automatically because the object you use as filter is not an observable, the function need to be re-called, either you pass in a scalar, but if you need an object make it observable with $: ...

**Comment by nimmolo** [comment]
Thanks, 

yes in this app the the filter would be easier to handle as an object (name, date, location, taxon, notes, orderby, order).
I tried making the filter object an observable:
```svelte
$: filter = {};
$: observations = GetObservations({ variables: { filter } });
```
But this didn't refetch when filter was changed, as I would expect it should. In Svelte, as far as I understand, the `$: observations` reactive declaration should change whenever `filter` changes, whether or not `filter` is an observable.

Your first suggestion works -- using `query.refetch` on the handleFilter function.
I initially declare the filter an empty object, and the filter form event changes the variable:
```svelte
let filter = {};

function handleFilter(event) {
  filter = event.detail;
  $observations.query.refetch({ filter }); 
  // note, passing the 'variables' key with the filter does not work: 
  // $observations.query.refetch({ variables: { filter } });
}
```
 
However both of these queries (including the refetch) are generating an error that did not occur before, when i was using svelte-apollo. 
Why am i getting this now?
```
Unhandled error localStorage is not defined Error: localStorage is not defined
    at new ApolloError (/Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/@apollo+client@3.5.4_graphql@15.7.2/node_modules/@apollo/client/errors/errors.cjs:34:28)
    at /Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/@apollo+client@3.5.4_graphql@15.7.2/node_modules/@apollo/client/core/core.cjs:1595:19
    at both (/Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/@apollo+client@3.5.4_graphql@15.7.2/node_modules/@apollo/client/utilities/utilities.cjs:986:53)
    at /Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/@apollo+client@3.5.4_graphql@15.7.2/node_modules/@apollo/client/utilities/utilities.cjs:979:72
    at new Promise (<anonymous>)
    at Object.then (/Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/@apollo+client@3.5.4_graphql@15.7.2/node_modules/@apollo/client/utilities/utilities.cjs:979:24)
    at Object.error (/Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/@apollo+client@3.5.4_graphql@15.7.2/node_modules/@apollo/client/utilities/utilities.cjs:987:49)
    at notifySubscription (/Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/xxx/Documents/GitHub/mo-sveltekit/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:240:7)
```

**Comment by ticruz38** [comment]
> Unhandled error localStorage is not defined Error: localStorage is not defined

you get an incompatibility for Apollo-client when your code is interpreted in the backend... You should configure Apollo-client as external or smith like that, this is an issue with svelte-kit not this plugin.

> let filter = {};
function handleFilter(event) {
  filter = event.detail;
  $observations.query.refetch({ filter }); 
  // note, passing the 'variables' key with the filter does not work: 
  // $observations.query.refetch({ variables: { filter } });
}

none of this works, you need to pass your variables under the variables field, otherwise the query is fetched without variables. If the query does not trigger with {variables: filter}, you probably pass the wrong variables to your query.

**Comment by nimmolo** [comment]
🙏 thanks for your patience, ticruz. I found my apollo-client error.

Everything's working now. 
Just a note: Although i do the initial query like, `$: observations = GetObservations({ variables: filter })`

TypeScript (or eslint) complains if i pass the `variables` key to refetch like this: 
`$observations.query.refetch({ variables: filter })`
It will only accept `$observations.query.refetch({ filter })`. But this refetch works :) The query is filtered.
