### ISSUE TITLE
Using subscribeToMore

### ISSUE THREAD

**Issue by maxxgl** [ticruz38/graphql-codegen-svelte-apollo#29]
Hi @ticruz38, thanks for the great library!

I was reading through the Apollo Docs (https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query), and got to wondering if it's possible to integrate Apollo's `subscribeToMore` function with this package?

Apologies if this is a bad question, I'm a bit new to the ecosystem.

**Comment by ticruz38** [comment]
You probably do not need this. Just change your query variables and it will refetch. For example if you want pagination just increase the pagination number as you scroll and the query will refetch.
Subscribe to more is supposed to work with normal query, this package only uses watchQueries.

**Comment by maxxgl** [comment]
I certainly don't _need_ it, but it is a nice convenience feature. I'm building out a live-chat feature, so I would say `subscribeToMore` is tailor-made for that use-case. I've already implemented my own solution, so its whatevs.
