### ISSUE TITLE
I think the documentation on your landing page is wrong.

### ISSUE THREAD

**Issue by bradphelan** [ticruz38/graphql-codegen-svelte-apollo#3]
I think the documentation on your landing page is wrong.

```
<ul>
{#each t?.data?.transactions || [] as transaction}
    <li>Sent transaction from {transaction.from} to {transaction.to}</li>
{/each}
</ul>
```
should be
```
<ul>
{#each $t?.data?.transactions || [] as transaction}
    <li>Sent transaction from {transaction.from} to {transaction.to}</li>
{/each}
</ul>
```

ie: missing **$** is front of the **t** on the **each** line

_Originally posted by @bradphelan in https://github.com/ticruz38/graphql-codegen-svelte-apollo/issues/2#issuecomment-732711663_

**Comment by ticruz38** [comment]
thanks @bradphelan I changed it ;)
