### ISSUE TITLE
pascalCase queries break generated code

### ISSUE THREAD

**Issue by AndreasHald** [ticruz38/graphql-codegen-svelte-apollo#8]
When queries are named using pascalCase as such
![Screenshot 2021-01-21 at 08 51 25](https://user-images.githubusercontent.com/8914722/105319947-dc70d880-5bc5-11eb-9240-19df6ced528b.png)

The corresponding types are created using CamelCase
![Screenshot 2021-01-21 at 08 52 03](https://user-images.githubusercontent.com/8914722/105320009-f14d6c00-5bc5-11eb-82eb-194c4c1f9593.png)

However the types used in the generated code use pascalCase, which does not exist.
![Screenshot 2021-01-21 at 08 53 14](https://user-images.githubusercontent.com/8914722/105320145-1c37c000-5bc6-11eb-870d-93d41832bf4d.png)

**Comment by ticruz38** [comment]
Yes, this could be configured, like other generator plugins that specify how the generated code should be treated UpperCamelCase or LowCamelCase. This one is UpperCamelCase by default.
It is still a bug as everything should either be Upper or LowCamelCase, I'll fix that this weekend.
Thanks for the report, pull request are welcome :)

**Comment by rumanHuq** [comment]
Is it fixed? I stumbled on the same issue :)
